### ISSUE TITLE
Не работает скачивание с pypi при использовании хуекера

### ISSUE THREAD

**Issue by nomilkinmyhome** [huecker-io/huecker#2]
### Description

при использовании хуекера почему-то перестает быть доступен pypi.org

я пингую pypi.org и все ок:

root@ctm:~/ctm-back# ping pypi.org
PING pypi.org (151.101.64.223) 56(84) bytes of data.
64 bytes from 151.101.64.223 (151.101.64.223): icmp_seq=1 ttl=56 time=37.5 ms
64 bytes from 151.101.64.223 (151.101.64.223): icmp_seq=2 ttl=56 time=37.7 ms
64 bytes from 151.101.64.223 (151.101.64.223): icmp_seq=3 ttl=56 time=37.7 ms

но при попытке в контейнере установить любой пакет с pypi идет ошибка 

84.26 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/asgiref/
99.35 ERROR: Could not find a version that satisfies the requirement asgiref==3.8.1 (from versions: none)
99.35 ERROR: No matching distribution found for asgiref==3.8.1

до установки хуекера такого поведения не наблюдалось

### Reproduce

1. установить хуекер по инструкции на офф сайте
2. написать Dockerfile

```
FROM python:3.11

WORKDIR /app

COPY . /app/

RUN apt update -y && apt upgrade -y
RUN pip install --upgrade pip && pip install -r requirements.txt

ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]
```
3. попробовать его сбилдить: `docker-compose build`

Все эти шаги проводились на сервере рег.ру 

### registry version

docker registry --version

Docker version 25.0.4, build 1a576c5

**Comment by altfoxie** [comment]
Не очень представляю, как источник образа может повлиять на работу сети.
<img width="826" alt="image" src="https://github.com/huecker-io/huecker/assets/26873765/aa917786-4b91-409b-b7d2-3bc41edbc187">
