### ISSUE TITLE
Не пуллится python:3.11-alpine

### ISSUE THREAD

**Issue by Seokky** [huecker-io/huecker#4]
### Description

ERROR: failed to solve: python:3.11-alpine: failed to resolve source metadata for docker.io/library/python:3.11-alpine: failed to do request: Head "https://huecker.io/v2/library/python/manifests/3.11-alpine?ns=docker.io": socks connect tcp 95.217.168.125:443->huecker.io:443: unknown error general SOCKS server failure

<img width="1404" alt="image" src="https://github.com/huecker-io/huecker/assets/26835215/64861f9e-f5f7-4ca6-91f4-734ce9572d97">

### Reproduce

`docker build -t mycontainer .`

```
FROM python:3.11-alpine

WORKDIR /usr/src/app
```

### registry version

~/.docker/daemon.json 

```
{
 "builder": {
  "gc": {
   "defaultKeepStorage": "20GB",
   "enabled": true
  }
 },
 "experimental": false,
 "proxies": {
   "https-proxy": "socks5://proxy.huecker.io:443",
   "no-proxy": "ghcr.io,*.test.example.com,.example.org,127.0.0.0/8"
 },
"registry-mirrors": ["https://huecker.io"]
}
```

**Comment by Seokky** [comment]
Попробовал спулить руками перед тем, как собирать образ
`docker pull python:3.11-alpine` внезапно помогло и проблема ушла

**Comment by altfoxie** [comment]
Привет! В конфиге одновременно указан и `registry-mirrors`, и SOCKS5 прокси. Docker пытается загрузить образ с `huecker.io`, но прокси допускает подключения только к Docker Hub.

Выберите один более удобный способ и используйте его. Но желательнее, конечно, SOCKS5)
